= ISBN like generator

The book store needs to generate the ISBN for each book before storing it (See BookResource).

This project aims at simulating an ISBN service.
As we aren't really generating any ISBN compatible string, we created a NumberResource.
The implementation is rather simple as it just returns a random number.

= How to test it?

With TomEE, it's possible to generate a fat and self container jar with the server and the application inside.

`mvn clean install -o`

On the `target/` directory, there is a `number-api-exec.jar` file.
It is 41MB which is seems quite big for a single class.
Indeed it contains also the TomEE application server in it.
With that in mind, we can now say, it's pretty small ;-)

Now, from a terminal, execute `java -jar target/number-api-exec.jar`.
The server should start and deploy my application

= Call it

Using a plain CURL command, it's possible to test our application running.

`curl -XGET http://localhost:8081/number-api/numbers/generate`

If you run that command multiple times, then you get a different number.

= Health check

http://localhost:8081/number-api/openapi.json

= Metrics

    @Metered(name="generateIsbnMetered", description = "Metrics for ISBN random generation")
    @Timed(name = "generateIsbnTimed",
            description = "Metrics to monitor the times of generate ISBN method.",
            unit = MetricUnits.MILLISECONDS,
            absolute = true)

http://localhost:8081/number-api/metrics
http://localhost:8081/number-api/metrics/base
http://localhost:8081/number-api/metrics/vendor
http://localhost:8081/number-api/metrics/application
http://localhost:8081/number-api/metrics/application/generateIsbnTimed

= all


```
@ApplicationScoped
@Path("numbers")
@Produces(MediaType.TEXT_PLAIN)
@Traced
@Tag(name = "ISBN resource", description = "Generate an ISBN number for a book.")
public class NumberResource {

    @GET
    @Path("generate")
    @Metered(description = "Metrics for ISBN random generation")
    @Timed(description = "Metrics to monitor the times of generate ISBN method.",
            unit = MetricUnits.MILLISECONDS,
            absolute = true)
    @Operation(description = "Generate an ISBN for a book.")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Successful, returning the value")
    })
    public Response generate() {
        return Response.ok(Math.random()).build();
    }
}
```
}

= Reporter demo

Go on http://localhost:8081/number-api/geronimo/microprofile/reporter/index.html
