---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: strimzi/kafka:0.11.4-kafka-2.1.0
          ports:
            - containerPort: 2181
          args:
            - sh
            - -c
            - bin/zookeeper-server-start.sh config/zookeeper.properties
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: strimzi/kafka:0.11.4-kafka-2.1.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          args:
            - sh
            - -c
            - bin/kafka-server-start.sh config/server.properties --override listeners=${KAFKA_LISTENERS}
              --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override
              zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}
      restartPolicy: Always

